version: '3'
services:

  api:
    build: './api'
    # api host port defined the same as in the container
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3001:3001"

  db:
    # This image exposes the standard MySQL port (3306)
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    # phpmyadmin port defined to 3002
    ports:
      - "3002:80"
    restart: always
